title: 'None'
url: 'https://none.github.io'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: None
tagline: None
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: none@example.com
phone:
website:
linkedin: none
github: none
twitter: '@none'


# Tracker
analytics: 'UA-99738090-1'
#Update all the sections by editing the files inside _includes folder.
